// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3TggHaMDpgsIEEuiU7So5iMA9_ikyI6U',
    appId: '1:698603939289:web:f73c3bf7ff99271961e5c8',
    messagingSenderId: '698603939289',
    projectId: 'tombola-8067d',
    authDomain: 'tombola-8067d.firebaseapp.com',
    storageBucket: 'tombola-8067d.firebasestorage.app',
    measurementId: 'G-W44SRB80TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtUx3xj6tJ_jBTZNC6eQFQToqSTtejSF8',
    appId: '1:698603939289:android:db8d6b4247ae477761e5c8',
    messagingSenderId: '698603939289',
    projectId: 'tombola-8067d',
    storageBucket: 'tombola-8067d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0U1Dn88NKQIQ3z_ZBW3JzAzCaw2qMvc',
    appId: '1:698603939289:ios:5642cad2451a208061e5c8',
    messagingSenderId: '698603939289',
    projectId: 'tombola-8067d',
    storageBucket: 'tombola-8067d.firebasestorage.app',
    iosBundleId: 'com.example.tombola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa0U1Dn88NKQIQ3z_ZBW3JzAzCaw2qMvc',
    appId: '1:698603939289:ios:5642cad2451a208061e5c8',
    messagingSenderId: '698603939289',
    projectId: 'tombola-8067d',
    storageBucket: 'tombola-8067d.firebasestorage.app',
    iosBundleId: 'com.example.tombola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3TggHaMDpgsIEEuiU7So5iMA9_ikyI6U',
    appId: '1:698603939289:web:2b04386723d54c9361e5c8',
    messagingSenderId: '698603939289',
    projectId: 'tombola-8067d',
    authDomain: 'tombola-8067d.firebaseapp.com',
    storageBucket: 'tombola-8067d.firebasestorage.app',
    measurementId: 'G-WR32M3X16X',
  );
}
